# Generated by Django 5.0.2 on 2024-02-19 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=15)),
                ('dob', models.DateTimeField()),
                ('gender', models.IntegerField()),
                ('designation', models.CharField(max_length=20)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
