# Generated by Django 5.0.2 on 2024-02-21 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='dob',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='employees',
            name='emp_id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employees',
            name='gender',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='employees',
            name='salary',
            field=models.CharField(),
        ),
    ]
