# Generated by Django 5.0.2 on 2024-02-28 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_employees_dob_alter_employees_emp_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employees',
            name='emp_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employees',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
