# Generated by Django 5.0.2 on 2024-02-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_employees_emp_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='join_date',
            field=models.DateField(null=True),
        ),
    ]
